bd/project/website/views.py
from flask import Blueprint, render_template, session, request, flash
from .models import Property
from . import db

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('ad_page.html', email=session.get('email'), role=session.get('role'), properties=Property.query.all())

@views.route('/Add_Property', methods=['POST', 'GET'])
def add_property():
    from .models import Property, House, Apartment, OtherProperty, Client
    
    if request.method == "POST":
        form_id = request.form.get('property_type')
        property_owner = request.form.get('property_owner')
        property_location = request.form.get('property_location')
        property_address = request.form.get('property_address')
        property_rent = request.form.get('property_rent')
        property_size = request.form.get('property_size')
        property_desc = request.form.get('property_description')

        new_property = Property(address=property_address, type=form_id, location=property_location, rent=property_rent, area=property_size, description=property_desc, owner_id=Client.query.filter_by(client_email=property_owner).first().id)

        if form_id == 'house':
            house_repair = request.form.get('house_repair')
            house_type = request.form.get('house_type')
            house_year = request.form.get('house_year')
            house_constr = request.form.get('house_construction')
            house_garage = request.form.get('garage')
            house_yard = request.form.get('yard')
            house_additional_land = request.form.get('additional_land')
            house_pets_allowed = request.form.get('pets_allowed')

            new_house = House(house_type=house_type, construction=house_constr, construction_year=house_year, garage=house_garage, parking_slot='F', yard=house_yard, land=house_additional_land, finished='T', repairs=house_repair, pet_friendly=house_pets_allowed, houses_address=property_address)

            print(new_house)
            print(new_property)

            db.session.add(new_property)
            db.session.add(new_house)
            db.session.commit()

        elif form_id == 'apartment':
            apartment_repair = request.form.get('apartment_repair')
            apartment_floor = request.form.get('apartment_floor')
            apartment_type = request.form.get('apartment_type')
            apartment_condition = request.form.get('apartment_condition')
            apartment_year = request.form.get('apartment_year')
            apartment_constr = request.form.get('apartment_construction')
            apartment_garage = request.form.get('garage')
            apartment_pets_allowed = request.form.get('pets_allowed')

            new_apartment = Apartment(apartment_type=apartment_type, flat=apartment_floor, construction=apartment_constr, construction_year=apartment_year, garage=apartment_garage, parking_slot='T', finished=apartment_condition, repairs=apartment_repair, pet_friendly=apartment_pets_allowed, apartments_address=property_address)
            print(new_apartment)
            print(new_property)
            db.session.add(new_property)
            db.session.add(new_apartment)
            db.session.commit()

        elif form_id == 'others':
            other_floor = request.form.get('other_floor')
            other_type = request.form.get('other_type')

            new_other = OtherProperty(flat=other_floor, other_properties_type=other_type, other_properties_address=property_address)
            print(new_other)
            print(new_other)
            db.session.add(new_property)
            db.session.add(new_other)
            db.session.commit()
        else:
            flash("Choose option", category="error")

    return render_template('AddProperty.html', email=session.get('email'), role=session.get('role'))

@views.route('/Properties')
def show_property():
    from .models import Client
    
    owner = Client.query.filter_by(client_email=session.get('email')).first()
    props = []
    
    if owner:
        props = Property.query.filter_by(owner_id=owner.id)

    return render_template('my_properties.html', email=session.get('email'), role=session.get('role'), properties=props)

@views.route('/Offices')
def show_offices():
    from .models import Office

    offices = Office.query.all()
    return render_template('Offices.html', offices=offices, email=session.get('email'), role=session.get('role'))

@views.route('/Staff')
def show_staff():
    from .models import Staff

    staff = Staff.query.all()
    return render_template('Staff.html', staff=staff, email=session.get('email'), role=session.get('role'))

@views.route('/Details/')
def show_details():
    return render_template('ad.html')
# @views.route('/Details/<address>')
# def show_details(address):
#     return render_template('ad.html', property=Property.query.filter_by(address=address).first())

bd/project/website/templates/AddProperty.html
{% extends "layout.html" %}

{% block head %}
	<title>Добавяне на обява</title>
	<link rel="stylesheet" href="../static/AddProperty.css">
{% endblock %}

{% block body %}
	<div class="container1">
		<div class="title">Добавяне на обява</div>
		<form method="POST" id="propertyForm">
			<div class="user-details">
				<p>Тип имот:</p>
				<input type="radio" id="house" name="property_type" value="house">
				<label for="house">Къща</label><br>
				<input type="radio" id="apartment" name="property_type" value="apartment">
				<label for="apartment">Апартамент</label><br>
				<input type="radio" id="others" name="property_type" value="others">
				<label for="others">Други имоти</label>
			</div>

			<div class="input-box">
				<span class="details">Собственик:</span>
				<input type="email" name="property_owner"  placeholder="въведи имейл на собственик"required>
			</div>

			<div class="input-box">
				<span class="details">Локация:</span>
				<input type="text" name="property_location"  placeholder="въведи локация"required>
			</div>

			<div class="input-box">
				<span class="details">Адрес:</span>
				<input type="text" name="property_address" placeholder="въведи адрес"required>
			</div>

			<div class="input-box">
				<span class="details">Наем на месец:</span>
				<input type="text" name="property_rent" placeholder="въведи наем"required>
			</div>

			<div class="input-box">
				<span class="details">Квадратура:</span>
				<input type="text" name="property_size" placeholder="въведи квадратура"required>
			</div>

			<div class="input-box">
				<span class="details">Описание:</span>
				<input type="text" name="property_description" placeholder="въведи описание на имота"required>
			</div>

			<div id="additionalFields"></div> <!-- Контейнер за допълнителните полета -->

			<div class="button">
				<input type="submit" value="Добави обява">
			</div>
		</form>
	</div>
	<script src="../static/AddProperty.js"></script>
{% endblock %}

bd/project/website/templates/Offices.html
{% extends "layout.html" %}

{% block head %}
	<title>Агенции</title>
	<link rel="stylesheet" href="../static/Agencies.css">
{% endblock %}

{% block body %}
	<div class="container1">
		<div class="title">Офиси</div>
		<form id="propertyForm">
			<div class="agencies">
				<div class="grid-container">
					{% for office in offices %}
					<div class="grid-item">
						<h3><i class="fa-solid fa-building"></i>{{ office.office_name }}</h3>
						<h3><i class="fa-icon fas fa-map-marker-alt"></i>{{ office.office_address }}</h3>
					</div>
					{% endfor %}
				</div>
			</div>
		</form>
	</div>
{% endblock %}

bd/project/website/templates/Staff.html
{% extends "layout.html" %}

{% block head %}
	<title>Агенции</title>
	<link rel="stylesheet" href="../static/Agencies copy.css">
{% endblock %}

{% block body %}
	<div class="container1">
		<div class="title">Служители</div>
		<form id="propertyForm">
			<div class="agencies">
				<div class="grid-container">
					{% for employee in staff %}
					<div class="grid-item">
						<h3><i class="fa-icon fas fa-map-marker-alt"></i>Офис: {{ employee.working_office }}</h3>
						<p><i class="fa-icon fas fa-user"></i>Име: {{ employee.staff_name }}</p>
						<p><i class="fa-icon fas fa-phone"></i>Тел: {{ employee.staff_phone_number }}</p>
					</div>
					{% endfor %}
				</div>
			</div>
		</form>
	</div>
{% endblock %}

bd/project/website/templates/ad.html
{% extends "layout.html" %}

{% block head %}
    <link rel="stylesheet" href="../static/big_ad_style.css">
    <title>Имоти под наем</title>
{% endblock %}

{% block body %}
    <div class="property-ad">
        <div class="description">
            <h1>Обява за Имот</h1>
            <p><strong>Тип имот:</strong> Къща</p>
            <p><strong>Локация:</strong>Студентски град</p>
            <p><strong>Адрес:</strong> ж.к Студентски град, N- 7</p>
            <p><strong>Наем на месец:</strong> 500лв</p>
            <p><strong>Квадратура:</strong> 40кв.м</p>
            <p><strong>Описание:</strong> Няма</p>
            <p><strong>Ремонт:</strong> Позволен</p>
            <p><strong>Вид:</strong> Етаж от къща</p>
            <p><strong>Година:</strong> 2007г.</p>
            <p><strong>Строителство:</strong> Тухла</p>
            <p><strong>Гараж:</strong> Да</p>
            <p><strong>Двор:</strong> Не</p>
            <p><strong>Допълнителна земя:</strong> Не</p>
            <p><strong>Позволени ли са домашни любимци:</strong> Да</p>
        </div>
        <div class="image">
            <img src="https://cdn1.vectorstock.com/i/1000x1000/73/70/isolated-flat-house-home-concept-simple-vector-13747370.jpg" alt="Снимка на имота">
        </div>
    </div>
{% endblock %}

bd/project/website/templates/ad_page.html
{% extends "layout.html" %}

{% block head %}
    <link rel="stylesheet" href="../static/ad_style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <title>Имоти под наем</title>
{% endblock %}

{% block body %}
    <div class="listings">
        <!-- <a href="{{ url_for('views.show_details') }}" class="listing">
            <div class="listing">
                <img src="https://via.placeholder.com/300" alt="Image">
                <h2>Заглавие на обява</h2>
                <p>Описание на имота. Това е примерна обява.</p>
                <p class="price">Цена: 0 лв.</p>
            </div>
        </a> -->
    
         {% for property in properties %}
            <a href="{{ url_for('views.show_details') }}" class="listing">
            <div class="listing">
                {% if property.type == 'house' %}
                    <img src="https://cdn1.vectorstock.com/i/1000x1000/73/70/isolated-flat-house-home-concept-simple-vector-13747370.jpg" alt="Image">
                {% elif property.type == 'apartment' %}
                    <img src="https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg" alt="Image">
                {% else%}
                    <img src="https://via.placeholder.com/300" alt="Image">
                {% endif %}
                <h2>{{ property.type }}</h2>
                <p>{{ property.description }}</p>
                <p class="price">Цена: {{ property.rent }} лв.</p>
            </div>
            </a>
         {% endfor %}
    </div>
    
    <script src="../static/script.js"></script>
{% endblock %}

bd/project/website/templates/layout.html
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <div class="container">
            <div class="logo">
                <img src="../static/logo.png" class="logo-img" alt="Logo">
                <h1>Rents</h1>
            </div>
            <nav>
                <ul>
                    <li><a href="/">Продажби</a></li>
                    <li><a href="/Offices">Офиси</a></li>
                    <li><a href="/Staff">Служители</a></li>
                    {% if not email %}
                        <li><a href="/Signin">Вход</a></li>
                    {% else %}
                        <li><a href="/Properties">Моите имоти</a></li>
                        {% if role == 'Staff' %}
                            <li><a href="/Add_Property">Добави обява</a></li>
                        {% endif %}
                        <li><a href="/Logout"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <main>
        {% block body %}{% endblock %}
    </main>
    <footer>
        <div class="container">
            <div class="footer-section">
                <h3>Контакти</h3>
                <p>Имейл: info@example.com</p>
                <p>Телефон: +359 123 456 789</p>
            </div>
            <div class="footer-section">
                <h3>Полезни връзки</h3>
                <ul>
                    <li><a href="#">Условия за ползване</a></li>
                    <li><a href="#">Политика за поверителност</a></li>
                    <li><a href="#">Често задавани въпроси</a></ли>
                </ul>
            </div>
            <div class="footer-section">
                <h3>Следвайте ни</h3>
                <ul class="social-media">
                    <li><a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a></li>
                    <li><a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

bd/project/website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/style_login.css">
    <title>GVK-Rent</title>
</head>
<body>
    <div class="container">
        <button onclick="location.href = '/';" class="exit">X</button>
        <div class="signin-signup">
            <form method="POST" class="sign-in-form">
                <h2 class="title">Sign in</h2>
                <input type="hidden" name="form_id" value="signin">
                <div class="input-field">
                    <i class="fa fa-user"></i>
                    <input autocomplete="off" required type="email" name="email_l" placeholder="Email">
                </div>
                <div class="input-field">
                    <i class="fa fa-lock"></i>
                    <input autocomplete="off" required type="password" name="password_l" placeholder="Password">
                </div>
                <div aria-required="true">
                    <input name="role" type="radio" value="Staff"> Брокер
                    <input name="role" type="radio" value="Client"> Клиент    
                </div>
                <input type="submit" value="Login" class="btn">
                <p class="account-text">Don't have an account? <a href="#" id="sign-up-btn2">Sign up</a></p>
            </form>
            <form method="POST" class="sign-up-form">
                <h2 class="title">Sign up</h2>
                <input type="hidden" name="form_id" value="signup">
                <div class="input-field">
                    <i class="fa fa-user"></i>
                    <input autocomplete="off" required type="text" name="username" placeholder="Username">
                </div>
                <div class="input-field">
                    <i class="fa fa-envelope"></i>
                    <input autocomplete="off" required type="email" name="email_r" placeholder="Email">
                </div>
                <div class="input-field">
                    <i class="fa fa-lock"></i>
                    <input required type="password" name="password_r" placeholder="Password">
                </div>
                <div class="input-field">
                    <i class="fa fa-phone"></i>
                    <input autocomplete="off" required type="text" name="number" placeholder="Phone Number">
                </div>
                <input type="submit" value="Sign up" class="btn">
                <p class="account-text">Already have an account? <a href="#" id="sign-in-btn2">Sign in</a></p>
            </form>
        </div>
        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3 class="site_name">GVK-Rent</h3>
                    <p>Чрез неповторимо обслужване и чудесни резултати, ние помагаме на нашите клиенти да постигнат целите си в сферата на недвижимите имоти в града, който обичаме</p>
                    <button class="btn" id="sign-in-btn">Sign in</button>
                </div>
                <img src="../static/signin.jpg" alt="" class="image">
            </div>
            <div class="panel right-panel">
                <div class="content">
                    <h3 class="site_name">GVK-Rent</h3>
                    <p>Чрез неповторимо обслужване и чудесни резултати, ние помагаме на нашите клиенти да постигнат целите си в сферата на недвижимите имоти в града, който обичаме</p>
                    <button class="btn" id="sign-up-btn">Sign up</button>
                </div>
                <img src="../static/signup.jpg" alt="" class="image">
            </div>
        </div>
    </div>
    <script src="../static/app.js"></script>
</body>
</html>

bd/project/website/templates/my_properties.html
{% extends "layout.html" %}

{% block head %}
    <title>Имоти под наем</title>
    <link rel="stylesheet" href="../static/my_properties.css">
{% endblock %}

{% block body %}
    <div class="listings">
        <!-- <a href="./ad.html" class="listing">    
            <div class="listing">
                <img src="https://via.placeholder.com/300" alt="Image">
                <h2>Заглавие на обява</h2>
                <p>Описание на имота. Това е примерна обява.</p>
                <p class="price">Цена: 0 лв.</p>
            </div>
        </a> -->
        
        {% for property in properties %}
        <a href="{{ url_for('views.show_details') }}" class="listing">
            <div class="listing">
                {% if property.type == 'house' %}
                    <img src="https://cdn1.vectorstock.com/i/1000x1000/73/70/isolated-flat-house-home-concept-simple-vector-13747370.jpg" alt="Image">
                {% elif property.type == 'apartment' %}
                    <img src="https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg" alt="Image">
                {% else%}
                    <img src="https://via.placeholder.com/300" alt="Image">
                {% endif %}
                <h2>{{ property.type }}</h2>
                <p>{{ property.description }}</p>
                <p class="price">Цена: {{ property.rent }} лв.</p>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

bd/project/website/templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
        </style>
</head>
<body>
    <h2>Users Table</h2>
    <table>
      <tr>
        <th>Clients ID</th>
        <th>email</th>
        <th>password</th>
      </tr>
      {% for client in clients %}
        <tr>
            <th>{{ client.id }}</th>
            <th>{{ client.client_email }}</th>
            <th>{{ client.client_password }}</th>
            <th></th>
        </tr>
      {% endfor %}
    </table>

    <h2>Staff Table</h2>
    <table>
      <tr>
        <th>Emp ID</th>
        <th>email</th>
        <th>password</th>
      </tr>
      {% for emp in staff %}
        <tr>
            <th>{{ emp.id }}</th>
            <th>{{ emp.staff_email }}</th>
            <th>{{ emp.staff_password }}</th>
        </tr>
      {% endfor %}
    </table>
</body>
</html>